language: python
python:
  - "3.6"
cache: pip

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - cp local_settings.py.example local_settings.py
  - pipenv run flake8
  - pipenv run python manage.py test
