language: python
python:
  - "3.6"
cache: pip

# Workaround for travis-ci/travis-ci#7940.
before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - cp local_settings.py.example local_settings.py
  - pipenv run flake8
  - pipenv run python manage.py test
