# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:47

from django.db import migrations, models
import django.db.models.deletion


def set_bidderid(apps, schema_editor):
    Bid = apps.get_model('artshow', 'Bid')
    for bid in Bid.objects.all():
        if bid.bidderid is None:
            bid.bidderid = bid.bidder.bidderid_set.first()


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidderid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artshow.BidderId'),
            preserve_default=False,
        ),
        migrations.RunPython(set_bidderid),
    ]
