# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 00:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0002_bid_bidderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='bids_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
