# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0004_bidder_details_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidderid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artshow.Bidder'),
        ),
    ]
