# Generated by Django 3.2.7 on 2021-12-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0008_remove_bidder_details_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('half_space', models.BooleanField(default=False, help_text='This location is a half-space that can only be allocated to a\n            single artist.')),
                ('space_is_split', models.BooleanField(default=False, help_text='Space counts as half for each artist.', verbose_name='Split')),
                ('artist_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artshow.artist')),
                ('artist_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artshow.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artshow.space')),
            ],
        ),
    ]
