# Generated by Django 4.2.6 on 2023-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0009_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Cash'), (3, 'Card')], default=0),
        ),
    ]
