# Generated by Django 4.2.6 on 2023-10-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0010_alter_invoicepayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquarePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artshow.payment')),
                ('payment_link_id', models.CharField(max_length=192)),
                ('payment_link_url', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=192)),
                ('payment_id', models.CharField(blank=True, max_length=192)),
            ],
            bases=('artshow.payment',),
        ),
    ]
