# Generated by Django 4.2.6 on 2023-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0011_squarepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('body', models.JSONField()),
            ],
        ),
    ]
