# Generated by Django 4.2.6 on 2023-11-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0012_squarewebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
