# Generated by Django 4.2.7 on 2023-12-11 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0013_squareterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareInvoicePayment',
            fields=[
                ('invoicepayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artshow.invoicepayment')),
                ('checkout_id', models.CharField(max_length=255)),
                ('payment_ids', models.TextField(blank=True)),
            ],
            bases=('artshow.invoicepayment',),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Cash'), (2, 'Check'), (3, 'Card'), (4, 'Other'), (5, 'Card')], default=0),
        ),
    ]
