# Generated by Django 5.1.4 on 2025-01-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0015_telegramwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessagingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
            ],
        ),
    ]
