# Generated by Django 5.1.4 on 2025-01-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0016_bulkmessagingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='squareterminal',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
