# Generated by Django 5.2.5 on 2025-09-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0017_squareterminal_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='allocated',
        ),
    ]
