# Generated by Django 5.2.6 on 2025-10-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshow', '0018_remove_allocation_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='print_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='print number within the run'),
        ),
        migrations.AddField(
            model_name='piece',
            name='print_run',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='size of the print run'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='buy_now',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='auto-buy price'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='min_bid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='minimum bid'),
        ),
    ]
