# Generated by Django 2.0.4 on 2018-04-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='address line 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reg_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Reg ID'),
        ),
    ]
