# Generated by Django 3.2.16 on 2022-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0003_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
