# Generated by Django 5.1.4 on 2024-12-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0005_person_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
