# Generated by Django 5.1.4 on 2025-01-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0006_person_email_phone_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
